create table if not exists public.contatos (
  id bigint generated by default as identity primary key,
  nome text not null,
  email text not null,
  telefone text not null,
  mensagem text not null,
  origem text not null default 'site',
  status text not null default 'novo',
  created_at timestamp with time zone not null default now()
);

alter table public.contatos enable row level security;
