create table if not exists public.testes (
  id bigint generated by default as identity primary key,
  nome text not null,
  created_at timestamp with time zone default now()
);

alter table public.testes enable row level security;

create policy "testes_select_public"
on public.testes
for select
to anon, authenticated
using (true);

create policy "testes_insert_public"
on public.testes
for insert
to anon, authenticated
with check (true);
